image: node:latest

variables:
  IMAGE_NAME: guizo792/clientui
  IMAGE_TAG: app
  DOCKER_REGISTRY_USER: guizo792
  DOCKER_REGISTRY_PASS: dckr_pat_dsXZ2z4kYEfgKw58WggXvgrt5kc
  CACHE_PATH: node_modules/

stages:
  - build
  - scan
  - publish
  - test

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

client-ui-build:
  stage: build
  before_script:
    - cd clientui
  script:
    - npm cache clean -f
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./build

client-ui-scan:
  stage: scan
  before_script:
    - cd clientui
  script:
    - npm install
    - npm audit fix --force
    - npm audit

client-ui-publish:
  stage: publish
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cd clientui
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS

  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
