image: node:latest

variables:
  IMAGE_NAME: guizo792/payment-ms
  IMAGE_TAG: app
  DOCKER_REGISTRY_USER: guizo792
  DOCKER_REGISTRY_PASS: dckr_pat_dsXZ2z4kYEfgKw58WggXvgrt5kc
  CACHE_PATH: node_modules/

stages:
  - build
  - scan
  - publish
  - test

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

payment-ms-build:
  stage: build
  before_script:
    - cd payment-ms
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
  cache:
    key: ${CACHE_PATH}-${CI_COMMIT_REF_SLUG}
    paths:
      - ${CACHE_PATH}

payment-ms-scan:
  stage: scan
  before_script:
    - cd payment-ms
  script:
    - npm install
    - npm audit

payment-ms-publish:
  stage: publish
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cd payment-ms
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASS

  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
