stages:
  - build

variables:
  DOCKER_IMAGE_NAME: product-service
  DOCKER_IMAGE_TAG: latest

before_script:
  - echo 'HERE WE GO...'

build:
  stage: build
  tags:
    - docker
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME:latest
