image: node:latest

variables:
  IMAGE_NAME: abdo20/product-ms
  IMAGE_TAG: app
  REGISTRY_USER: abdo20
  REGISTRY_PASS: dckr_pat_dsXZ2z4kYEfgKw58WggXvgrt5kc
  CACHE_PATH: node_modules/

stages:
  - build
  - scan
  - publish
  - test

include:
  - template: Security/Dependency-Scanning.gitlab-ci.yml

product-ms-build:
  stage: build
  before_script:
    - cd product-ms
  script:
    - npm install
  artifacts:
    paths:
      - node_modules
  cache:
    key: ${CACHE_PATH}-${CI_COMMIT_REF_SLUG}
    paths:
      - ${CACHE_PATH}

product-ms-scan:
  stage: scan
  before_script:
    - cd product-ms
  script:
    - npm install
    - npm audit

product-ms-publish:
  stage: publish
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - cd product-ms
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS

  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
