stages:
  - build

variables:
  DOCKER_IMAGE_NAME: product-service
  DOCKER_IMAGE_TAG: latest
  DOCKER_REGISTRY_USER: guizo792
  DOCKER_REGISTRY_TOKEN: dckr_pat_dsXZ2z4kYEfgKw58WggXvgrt5kc

build:
  stage: build
  tags:
    - docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"

  before_script:
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_TOKEN
    - cd product-ms
  script:
    - docker build -t $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG .
    - docker tag $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG $DOCKER_IMAGE_NAME:latest
    - docker push $DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG
